In [21]:
# Задание 1 
import numpy as np
M=int(input())
m = np.arange(M-1,-1,-1)
print(m)

13
[12 11 10  9  8  7  6  5  4  3  2  1  0]


In [22]:
# Задание 2
m_d = np.diag(m, k = 0)
print(m_d)

[[12  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0 11  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0 10  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  9  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  8  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  7  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  6  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  5  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  4  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  3  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  2  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  1  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0]]


In [23]:
np.sum(np.diag(m, k = 0))

78

In [24]:
# Задание 3
A = np.array([[4,2,1], [1,3,0], [0,5,4]])
B = np.array([4,12,-3])

In [25]:
from numpy import linalg
linalg.solve(A,B)

array([ 0.46666667,  3.84444444, -5.55555556])

In [26]:
np.allclose(np.dot(A,linalg.solve(A,B)),B)

True

In [7]:
# Задание 4
import pandas as pd

In [8]:
l = pd.read_csv('visit_log.csv', sep=';')
l.head()

timestamp    visit_id                                 url  region  \
0  1549980692  e3b0c44298  https://host.ru/3c19b4ef7371864fa3  Russia   
1  1549980704  6e340b9cff  https://host.ru/c8d9213a31839f9a3a  Russia   
2  1549980715  96a296d224  https://host.ru/b8b58337d272ee7b15  Russia   
3  1549980725  709e80c884  https://host.ru/b8b58337d272ee7b15  Russia   
4  1549980736  df3f619804  https://host.ru/b8b58337d272ee7b15  Russia   

      user_id traffic_source  
0  b1613cc09f         yandex  
1  4c3ec14bee         direct  
2  a8c40697fb         yandex  
3  521ac1d6a0         yandex  
4  d7323c571c         yandex

In [9]:
l.loc[:,['traffic_source','region']].head(10)

traffic_source  region
0         yandex  Russia
1         direct  Russia
2         yandex  Russia
3         yandex  Russia
4         yandex  Russia
5         yandex  Russia
6           paid  Russia
7         direct  Russia
8         direct   China
9          email  Russia

In [10]:
def filtered(row):
    if row['traffic_source']=='yandex':
        return 'organic'
    elif row['traffic_source']=='google':
        return 'organic'
    elif row['traffic_source']=='paid':
        if row['region']=='Russia':
            return 'ad'
        else:
            return 'other'
    elif row['traffic_source']=='email':
        if row['region']=='Russia':
            return 'ad'
        else:
            return 'other'
    else:
        return row['traffic_source']

In [11]:
l['source_type']=l.apply(filtered, axis=1)
l.head(10)

timestamp    visit_id                                 url  region  \
0  1549980692  e3b0c44298  https://host.ru/3c19b4ef7371864fa3  Russia   
1  1549980704  6e340b9cff  https://host.ru/c8d9213a31839f9a3a  Russia   
2  1549980715  96a296d224  https://host.ru/b8b58337d272ee7b15  Russia   
3  1549980725  709e80c884  https://host.ru/b8b58337d272ee7b15  Russia   
4  1549980736  df3f619804  https://host.ru/b8b58337d272ee7b15  Russia   
5  1549980742  8855508aad  https://host.ru/df646c3676cc259fa0  Russia   
6  1549980742  b0f66adc83  https://host.ru/b8b58337d272ee7b15  Russia   
7  1549980754  837885c8f8  https://host.ru/108ce4b365afb7b88e  Russia   
8  1549980760  af5570f5a1  https://host.ru/3004a8273caeef2867   China   
9  1549980765  3e7077fd2f  https://host.ru/df646c3676cc259fa0  Russia   

      user_id traffic_source source_type  
0  b1613cc09f         yandex     organic  
1  4c3ec14bee         direct      direct  
2  a8c40697fb         yandex     organic  
3  521ac1d6a0         yandex     organic  
4  d7323c571c         yandex     organic  
5  fc43898e47         yandex     organic  
6  13fc55e781           paid          ad  
7  cb5082b6f6         direct      direct  
8  45664f7af2         direct      direct  
9  6f9de8c8b6          email          ad

In [12]:
# Задание 5
import pandas as pd
import re

In [13]:
URLs = pd.read_table('URLs.txt')
URLs.head()

url
0                                            /world/
1                                           /latest/
2                                      /?updated=top
3  /politics/36188461-s-marta-zhizn-rossiyan-susc...
4  /world/36007585-tramp-pridumal-kak-reshit-ukra...

In [15]:
URLs[URLs.url.str.contains('/[0-9]{8}-', regex=True)].head()

url
3  /politics/36188461-s-marta-zhizn-rossiyan-susc...
4  /world/36007585-tramp-pridumal-kak-reshit-ukra...
5  /science/36157853-nasa-sobiraet-ekstrennuyu-pr...
6  /video/36001498-poyavilis-pervye-podrobnosti-g...
7  /world/36007585-tramp-pridumal-kak-reshit-ukra...

In [ ]:
# Задание 6

In [16]:
pip install pymystem3

Note: you may need to restart the kernel to use updated packages.


In [17]:
from pymystem3 import Mystem
import pandas as pd

In [18]:
d = pd.DataFrame({
    'keyword': ['курс гривны к рублю', 'доллары в рубли', '100 долларов в рублях', 'курс рубля'],
    'shows': [125076, 114173, 97534, 53546],
})

In [19]:
def lem_f(row):
    m=Mystem()
    lemma = m.lemmatize(row['keyword'])
    string = ' '.join(lemma)
    return string

In [20]:
d['lemmas']=d.apply(lem_f, axis=1)
d.head()

keyword   shows                        lemmas
0    курс гривны к рублю  125076  курс   гривна   к   рубль \n
1        доллары в рубли  114173         доллар   в   рубль \n
2  100 долларов в рублях   97534   100   доллар   в   рубль \n
3             курс рубля   53546               курс   рубль \n